@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.datasync;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;