@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.resources;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;